default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: akeems
  password: testpass

development:
  <<: *default
  database: trippappdatabase
  
  

# test:
#   <<: *default
#   database: trippappdatabase
#   username: akeemtest
#   password: testpass


# production:
#   <<: *default
#   database: tripappdatabase
#   username: akeemtest
#   password: testpass
