FROM ruby:2.7.4-alpine@sha256:4f8e01030cbfc0c4521f03dde723aeb3b2d38349022275634a4c03be384d7212

RUN apk add \
    build-base \
    postgresql-dev \
    tzdata \
    nodejs

WORKDIR /app
COPY backend/Gemfile .
COPY backend/Gemfile.lock .
RUN bundle install
COPY backend .
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]